name: Deploy to VServer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Deploy with rsync
      uses: burnett01/rsync-deployments@master
      with:
        switches: -avz --delete --exclude='.git/'
        path: ./*
        remote_path: /var/www/coffee.thorgerjansen.de/
        remote_host: ${{ secrets.SERVER_IP }}
        remote_user: ${{ secrets.SERVER_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_port: 2222
